<?php


namespace app\modules\v1\controllers;

use yii\data\ActiveDataProvider;
use yii\db\Query;
use yii\rest\Controller;

class KorisnikController extends Controller
{
  public function actionIndex()
  {
    $query = new Query();

    $query->from('Korisnik')
      ->join('Inner Join', 'Prijava', 'Prijava.ID_Korisnik = Korisnik.ID')
      ->select('Prijava.ID as ID_Prijave, 
      Prijava.Opis as Opis_Prijave, 
      Korisnik.Ime, 
      Korisnik.Prezime'
      );

    return new ActiveDataProvider(['query' => $query]);
  }

  public function behaviors()
  {
    return parent::behaviors(); // TODO: Change the autogenerated stub
  }
}