<?php


namespace app\modules\v1\controllers;

use yii\data\ActiveDataProvider;
use yii\db\Query;
use yii\rest\Controller;

class NovostiController extends Controller
{
  public function actionIndex()
  {

    $query = new Query();

    $query->from('Novost')
      ->join('Inner Join', 'Prijava', 'Novost.ID = Prijava.ID_Novost')
      ->join('Inner Join', 'StanjeTerena', 'Prijava.ID = StanjeTerena.ID_Prijava')
      ->join('Inner Join', 'Korisnik', 'Novost.ID_Korisnik = Korisnik.ID')
      ->select(
        'Novost.Opis as Opis_Novosti, Novost.Vrijeme_Objave as Vrijeme_Novosti, 
      Prijava.Opis as Opis_Prijave, Prijava.Vrijeme_Prijave as Vrijeme_Prijave, 
      StanjeTerena.Opis, StanjeTerena.Trajanje, 
      StanjeTerena.Broj_Vatrogasaca, StanjeTerena.Broj_Vozila,
      Korisnik.Korisnicko_Ime as Autor');

    return new ActiveDataProvider(['query' => $query]);
  }

  public function behaviors()
  {
    return parent::behaviors(); // TODO: Change the autogenerated stub
  }
}