<?php


namespace app\modules\v1\controllers;

use yii\db\Query;
use yii\rest\Controller;

class NovostiController extends Controller
{
  public function actionIndex()
  {

    $query = new Query();

    $query->from('Novost')
      ->join('Left Join', 'Prijava', 'Novost.ID = Prijava.ID_Novost')
      ->join('Inner Join', 'Korisnik', 'Novost.ID_Korisnik = Korisnik.ID')
      ->select(
        'Korisnik.Korisnicko_Ime as Autor, Novost.Naslov as Naslov_Novosti, Novost.Opis as Opis_Novosti, 
        Novost.Vrijeme_Objave as Vrijeme_Novosti, Prijava.Opis as Opis_Prijave, 
        Prijava.Vrijeme_Prijave as Vrijeme_Prijave');

    return $query->all();
  }

  public function behaviors()
  {
    return parent::behaviors(); // TODO: Change the autogenerated stub
  }
}