<?php


namespace app\modules\v1\controllers;


use yii\rest\ActiveController;

class PrijavaController extends ActiveController
{
  public $modelClass = 'app\models\Prijava';

  public function actions()
  {
    return [
      'view' => [
        'class' => 'yii\rest\ViewAction',
        'modelClass' => $this->modelClass,
        'checkAccess' => [$this, 'checkAccess'],
      ],
      'create' => [
        'class' => 'yii\rest\CreateAction',
        'modelClass' => $this->modelClass,
        'checkAccess' => [$this, 'checkAccess'],
        'scenario' => $this->createScenario,
      ],
      'update' => [
        'class' => 'yii\rest\UpdateAction',
        'modelClass' => $this->modelClass,
        'checkAccess' => [$this, 'checkAccess'],
        'scenario' => $this->updateScenario,
      ]
    ];
  }

  public function behaviors()
  {
    return parent::behaviors(); // TODO: Change the autogenerated stub
  }
}