<?php


namespace app\modules\v1\controllers;


use app\models\Prijava;
use yii\db\Query;
use yii\rest\ActiveController;

class PrijavaController extends ActiveController
{
  public $modelClass = 'app\models\Prijava';

  public function actions()
  {
    $actions = parent::actions();
    unset($actions['view']);
    return [
      'create' => [
        'class' => 'yii\rest\CreateAction',
        'modelClass' => $this->modelClass,
        'checkAccess' => [$this, 'checkAccess'],
        'scenario' => $this->createScenario,
      ],
    ];
  }

  public function behaviors()
  {
    return parent::behaviors(); // TODO: Change the autogenerated stub
  }

  public function actionView($id){
    $query = new Query();
    $query->from('Prijava')
      ->join('Inner Join', 'Korisnik', 'Prijava.ID_Korisnik = Korisnik.ID')
      ->select("Prijava.ID as ID_Prijave, Opis,Lat, Long, Odobreno")
      ->where(['Korisnik.ID' => $id]);

    return $query->all();
  }

  public function actionIndex(){
    return Prijava::find()->select(['ID', 'Opis'])->all();
  }
}