<?php


namespace app\modules\v1\controllers;


use yii\rest\ActiveController;

class StanjeTerenaController extends ActiveController
{
  public $modelClass = 'app\models\StanjeTerena';

  public function behaviors()
  {
    return parent::behaviors(); // TODO: Change the autogenerated stub
  }
}