<?php


namespace app\modules\v1\controllers;


use yii\rest\ActiveController;

class StanjeTerenaController extends ActiveController
{
  public $modelClass = 'app\models\StanjeTerena';

  public function actions()
  {
    return [
      'create' => [
        'class' => 'yii\rest\CreateAction',
        'modelClass' => $this->modelClass,
        'checkAccess' => [$this, 'checkAccess'],
        'scenario' => $this->createScenario,
      ],
    ];
  }

  public function behaviors()
  {
    return parent::behaviors(); // TODO: Change the autogenerated stub
  }
}